const REGISTER = 'REGISTER'
const LOGIN = 'LOGIN'
const REFRESH = 'REFRESH'
const LOGOUT = 'LOGOUT'
const CREATE_FINGERPRINT = 'CREATE_FINGERPRINT'
const CHANGE_EMAIL = 'CHANGE_EMAIL'
const CHANGE_PSW = 'CHANGE_PSW'
const CHANGE_ADDITIONAL = 'CHANGE_ADDITIONAL'
const DELETE_USER = 'DELETE_USER'

export { REGISTER, LOGIN, REFRESH, LOGOUT, CREATE_FINGERPRINT, CHANGE_EMAIL, CHANGE_PSW, CHANGE_ADDITIONAL, DELETE_USER }
