import { REGISTER, LOGIN, REFRESH, LOGOUT, CREATE_FINGERPRINT, CHANGE_ADDITIONAL, CHANGE_PSW, CHANGE_EMAIL, DELETE_USER } from './actions.types'
import actions from '@/app/store/actions/actions'

export default actions
export { REGISTER, LOGIN, REFRESH, LOGOUT, CREATE_FINGERPRINT, CHANGE_EMAIL, CHANGE_PSW, CHANGE_ADDITIONAL, DELETE_USER }
